package Vista;

import Controlador.Lista_compra;
import Modelo.JavaConexion;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Daniel
 */
public class panel_comprar extends javax.swing.JPanel {

    JavaConexion BD;
    String Nombre, cedula;

    public panel_comprar() {
        initComponents();
        this.setSize(750, 550);
    }

    @Override
    public void paint(Graphics g) {
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/mejorcalidadcomprar.jpg"));;
        g.drawImage(icon.getImage(), 0, 0, this.getWidth(), this.getHeight(), this);
        this.setOpaque(false);
        super.paint(g);
    }

    public void getcredenciales(String Nombre, String cedula, JavaConexion BD) {
        this.BD = BD;
        this.Nombre = Nombre;
        this.cedula = cedula;
        presentacion.setText("BIENVENIDO " + Nombre + " [" + BD.estatus(Nombre, cedula) + "]");
        if (BD.estatus(Nombre, cedula).equals("cliente")) {
            comprar.setEnabled(false);
        }
    }

    //Metodo para dar los titulos a la tabla
    public void Mostrar_productos(String filtro) {
        Lista_compra lista = new Lista_compra();
        String cabecera[] = {"ID", "NOMBRE", "CANTIDAD EXISTENTE", "PRECIO", "PESO", "CARACTERISTICAS"};
        String Datos[][] = lista.Listado_compra(BD, filtro);
        Tabla = new JTable(Datos, cabecera);
        Scroll.setViewportView(Tabla);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Scroll = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filtro = new javax.swing.JTextField();
        comprar = new javax.swing.JButton();
        presentacion = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cantidad1 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Comprar Buff GYM");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 230, 50));

        Tabla.setBackground(new java.awt.Color(51, 51, 51));
        Tabla.setForeground(new java.awt.Color(255, 255, 255));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Scroll.setViewportView(Tabla);

        add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 710, 190));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar por Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Digite la cantidad a comprar");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, 30));

        filtro.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        filtro.setForeground(new java.awt.Color(0, 0, 0));
        filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtroKeyReleased(evt);
            }
        });
        add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 130, 30));

        comprar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        comprar.setText("COMPRAR");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });
        add(comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 150, 50));

        presentacion.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        presentacion.setForeground(new java.awt.Color(255, 255, 255));
        presentacion.setText("Compra de");
        add(presentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 550, 60));

        ID.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(51, 51, 51));
        add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 100, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Digite el ID del producto que desea comprar");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 400, 30));

        cantidad1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cantidad1.setForeground(new java.awt.Color(0, 0, 0));
        add(cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        // TODO add your handling code here:
        int id_producto = Integer.parseInt(ID.getText());
        if (BD.Validar_producto(id_producto)) {
            int canti = Integer.parseInt(cantidad1.getText());
            if (BD.validar_cantidad(id_producto, canti)) {
                BD.Modificar_cantidad(id_producto, canti);
                JOptionPane.showMessageDialog(null, "Su compra se a realizado exitosamente. \n"
                        + "Total a pagar: " + BD.Cantidad_pagar(id_producto, canti),
                        "INFORMACION DE COMPRA ", JOptionPane.INFORMATION_MESSAGE);
                 Mostrar_productos("");
            } else {
                JOptionPane.showMessageDialog(null, "La cantidad sobrepasa la existente, digite una cantidad valida con respecto el producto  porfavor.",
                        "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "El producto no existe, porfavor digite bien el ID",
                    "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_comprarActionPerformed

    private void filtroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroKeyReleased
        // TODO add your handling code here:
        Mostrar_productos(filtro.getText().trim());
    }//GEN-LAST:event_filtroKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField cantidad1;
    private javax.swing.JButton comprar;
    private javax.swing.JTextField filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel presentacion;
    // End of variables declaration//GEN-END:variables
}
